# Generated by Django 3.2.15 on 2022-08-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=50, max_digits=100)),
                ('dateProduced', models.DateTimeField()),
                ('dateLastLaunched', models.DateTimeField()),
            ],
        ),
    ]
