# Generated by Django 3.2.15 on 2022-08-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rocket',
            old_name='model',
            new_name='version',
        ),
    ]
